name: Ejemplo CI/CD

on: [push]

jobs:
  inicio:
    runs-on: macos-latest
    #Pasos
    steps:
      - name: mostrar texto
        run: echo "Hola mundo"
  build:
    runs-on: macos-latest
    needs: [inicio]
    steps:
      - name: mostrar texto
        run: echo "Adios"