name: Ejemplo CI/CD

on: [push]

jobs:
  inicio:
    runs-on: macos-latest
    #Pasos
    steps:
      - name: texto
        run: echo "Pasos para clonar repositorios a github actions"
      - name: Checkout
        uses: actions/checkout@v4.2.2
  build:
    runs-on: macos-latest
    needs: [inicio]
    steps:
      - name: mostrar texto
        run: echo "Adios"
  test:
    runs-on: macos-latest
    needs: [build]
    steps:
      - name: mostrar texto
        run: echo "test"
  deploy:
    runs-on: macos-latest
    needs: [test]
    steps:
      - name: mostrar texto
        run: echo "deploy"