name: Ejemplo CI/CD

on: [push]

jobs:
  inicio:
    runs-on: macos-latest
    #Pasoso
    steps:
      - name: mostrar texto
        run: echo "Hola mundo"
  bluid:
      runs-on: macos-latest
      needs: [inicio]
      steps:
        - name: texto
          run: echo "Construir"

